spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false

  messages:
    basename: messages, errors

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}

pay:
  callback:
    fail-url: ${PAY_CALLBACK_FAIL_URL}
    success-url: ${PAY_CALLBACK_SUCCESS_URL}
  toss:
    secret-key: ${PAY_TOSS_SECRET_KEY}
